src/main/java/com/matdori/matdori/domain/Jokbo.java, src/main/java/com/matdori/matdori/domain/JokboComment.java, src/main/java/com/matdori/matdori/domain/JokboCommentComplain.java, src/main/java/com/matdori/matdori/domain/JokboComplain.java, src/main/java/com/matdori/matdori/domain/JokboFavorite.java, src/main/java/com/matdori/matdori/domain/JokboImg.java, src/main/java/com/matdori/matdori/domain/Notice.java
=> 테이블 JPA 코드 작성(족보, 공지사항)

src/main/java/com/matdori/matdori/domain/Category.java, src/main/java/com/matdori/matdori/domain/Menu.java, src/main/java/com/matdori/matdori/domain/OpenHours.java, src/main/java/com/matdori/matdori/domain/PopularMenu.java, src/main/java/com/matdori/matdori/domain/Store.java, src/main/java/com/matdori/matdori/domain/StoreFavorite.java
=> 테이블 JPA 코드 작성(가게)

src/main/java/com/matdori/matdori/domain/User.java
=> 테이블 JPA 코드 작성(유저)

src/main/java/com/matdori/matdori/domain/TermAgreement.java, src/main/java/com/matdori/matdori/domain/TermsOfService.java
=> 테이블 JPA 코드 작성(약관)

src/main/java/com/matdori/matdori/controller/UserApiController.java, src/main/java/com/matdori/matdori/domain/Store.java, src/main/java/com/matdori/matdori/domain/StoreFavorite.java, src/main/java/com/matdori/matdori/domain/User.java, src/main/java/com/matdori/matdori/repositoy/StoreFavoriteRepository.java, src/main/java/com/matdori/matdori/repositoy/UserRepository.java, src/main/java/com/matdori/matdori/service/UserService.java
=> feat : Create createFavoriteStore API

src/main/java/com/matdori/matdori/exception/ErrorCode.java, src/main/java/com/matdori/matdori/exception/ExceptionManager.java
=> feat : create ErrorCode, ExceptionManager Class

.gitignore, build.gradle, src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/domain/Jokbo.java, src/main/java/com/matdori/matdori/domain/JokboComment.java, src/main/java/com/matdori/matdori/domain/JokboCommentComplain.java, src/main/java/com/matdori/matdori/domain/JokboComplain.java, src/main/java/com/matdori/matdori/domain/JokboImg.java, src/main/java/com/matdori/matdori/domain/Notice.java, src/main/java/com/matdori/matdori/repositoy/JokboImgRepository.java, src/main/java/com/matdori/matdori/repositoy/JokboRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java, src/main/java/com/matdori/matdori/service/S3UploadService.java
=> 족보 작성하기 기능 구현

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/exception/ExceptionManager.java, src/main/java/com/matdori/matdori/service/JokboService.java
=> 족보 내용 조회 기능 구현

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/repositoy/JokboImgRepository.java, src/main/java/com/matdori/matdori/repositoy/JokboRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java, src/main/java/com/matdori/matdori/service/S3UploadService.java
=> 예외 처리를 없는 족보 삭제 기능 구현 완료

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/domain/Jokbo.java, src/main/java/com/matdori/matdori/repositoy/JokboCommentRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java
=> 예외처리 없는 족보 댓글 등록하기 기능 구현 완료.

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/repositoy/JokboCommentRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java
=> feat: 족보에 매핑된 모든 댓글 조회하기 기능 구현

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/repositoy/JokboCommentRepository.java, src/main/java/com/matdori/matdori/repositoy/JokboRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java
=> 족보 댓글 삭제하기 기능 구현.

src/main/java/com/matdori/matdori/domain/Jokbo.java, src/main/java/com/matdori/matdori/domain/User.java, src/main/java/com/matdori/matdori/repositoy/JokboFavoriteRepository.java
=> jokboFavoriteRepository 작성

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/service/JokboService.java
=> 족보의 총 개수 조회하기 기능 구현.

src/main/java/com/matdori/matdori/domain/Jokbo.java
=> 족보 도메인에 cascade 적용.

src/main/java/com/matdori/matdori/controller/JokboApiController.java
=> DTO 필드명 카멜케이스로 변경.

src/main/java/com/matdori/matdori/controller/JokboApiController.java
족보 api 컨트롤러 request DTO들에 not null 및 not blank 처리.
=> 족보 api 컨트롤러 request DTO들에 not null 및 not blank 처리.

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/domain/Store.java, src/main/java/com/matdori/matdori/repositoy/StoreRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java, src/main/java/com/matdori/matdori/service/StoreService.java
=> 학과별 추천 식당 조회 기능 구현

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/repositoy/Dto/MatdoriPick.java, src/main/java/com/matdori/matdori/repositoy/StoreRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java
=> 맛도리픽 기능 구현.

src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/repositoy/Dto/JokboRichStore.java, src/main/java/com/matdori/matdori/repositoy/StoreRepository.java, src/main/java/com/matdori/matdori/service/JokboService.java
=> 족보 부자 가게 리스트 조회하기 기능 구현.

src/main/java/com/matdori/matdori/controller/EtcApiController.java, src/main/java/com/matdori/matdori/domain/Notice.java, src/main/java/com/matdori/matdori/repositoy/NoticeRepository.java, src/main/java/com/matdori/matdori/service/EtcService.java
=> 공지사항 리스트 조회하기 기능 구현

src/main/java/com/matdori/matdori/controller/EtcApiController.java, src/main/java/com/matdori/matdori/service/EtcService.java
=> 공지사항 글 조회하기 기능 구현.

src/main/java/com/matdori/matdori/controller/EtcApiController.java, src/main/java/com/matdori/matdori/service/EtcService.java
=> 이용약관 리스트 불러오기 기능 구현.

src/main/java/com/matdori/matdori/controller/EtcApiController.java, src/main/java/com/matdori/matdori/controller/JokboApiController.java, src/main/java/com/matdori/matdori/controller/StoreApiController.java, src/main/java/com/matdori/matdori/controller/UserApiController.java, src/main/java/com/matdori/matdori/repositoy/JokboRepository.java, src/main/java/com/matdori/matdori/service/AuthorizationService.java, src/main/java/com/matdori/matdori/service/JokboService.java, src/main/java/com/matdori/matdori/service/MailService.java, src/main/java/com/matdori/matdori/service/S3UploadService.java, src/main/java/com/matdori/matdori/service/UserService.java
=> 코드 리뷰 및 수정사항 체크

src/main/java/com/matdori/matdori/controller/StoreApiController.java, src/main/java/com/matdori/matdori/controller/UserApiController.java, src/main/java/com/matdori/matdori/domain/Store.java, src/main/java/com/matdori/matdori/domain/StoreCategory.java, src/main/java/com/matdori/matdori/exception/ErrorCode.java, src/main/java/com/matdori/matdori/exception/ExceptionManager.java, src/main/java/com/matdori/matdori/exception/NotExistStoreCategoryException.java
feat : 존재하는 가게인지 체크하는 로직 추가 및 가게카테고리 enum 생성
=> feat : 존재하는 가게인지 체크하는 로직 추가 및 가게카테고리 enum 생성
